#ifndef HEADER_WBCRYPTO_RAND_WBCRYPTO_RAND_H
#define HEADER_WBCRYPTO_RAND_WBCRYPTO_RAND_H

#if !defined(TARGET_PLATFORM_ANDROID)
// Config file is generated by cmake
#include "wbcrypto/config.h"
#endif

#if defined(WBCRYPTO_RAND_VER_WBCRYPTO)

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>

#include <WbcryptoRand/hmac_drbg.h>
#include <WbcryptoRand/md.h>

#ifdef __cplusplus
extern "C" {
#endif

// ------------------------------
// Cmake config -> Local config
//

// ------------------
// 1. Hash Algorithm
//

// SM3 as Hash Algorithm
#ifdef WBCRYPTO_RAND_HASH_ALG_SM3
#define RANDOM_HASH_ALGORITHM MD_SM3
#endif

// Control HMAC-DRBG Hash Algorithm
// Attention! Use #define to set it
#ifndef RANDOM_HASH_ALGORITHM
#error "Must set Wbcrypto Rand Hash Algorithm!"
#endif

// ------------------
// 2. iOS Sensors
//

// #define WBCRYPTO_RAND_ENABLE_SEED_IOS_SENSOR

// ------------ END ------------
//

static unsigned int WbcryptoRandomContextCount = 0;

// HMAC-DRBG Random Class
struct wbcrypto_rand_context {
    short isInitial;
    short isSeeded;

    unsigned char hashLen;
    unsigned char *hash;

    const wbcrypto_md_info_t *md_info;     /*!<  Hash Type Info    */
    wbcrypto_md_context_t md_ctx;         /*!<  MD Context        */
    wbcrypto_hmac_drbg_context drbg_ctx;  /*!<  HMAC DRBG Context */
};

#ifdef __cplusplus
}
#endif

#endif /* END WBCRYPTO_RAND_VER_WBCRYPTO */

#endif /* END HEADER_WBCRYPTO_RAND_WBCRYPTO_RAND_H */
